import localFont from "next/font/local";
import "./globals.css";
import TanstackProvider from "./provider/tanstackProvider";

const estrella = localFont({
  src: "../public/fonts/Estrella.otf",
  variable: "--font-estrella",
  weight: "400",
});

const advercaseRegular = localFont({
  src: "../public/fonts/Advercase-Regular.otf",
  variable: "--font-advercase-regular",
  weight: "400",
});

const advercaseBold = localFont({
  src: "../public/fonts/Advercase-Bold.otf",
  variable: "--font-advercase-bold",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TanstackProvider>
        <body
          className={`${estrella.variable} ${advercaseRegular.variable} ${advercaseBold.variable}`}
        >
          {children}
        </body>
      </TanstackProvider>
    </html>
  );
}
